### ISSUE TITLE
Logout fails due to it being a GET request not a POST request

### ISSUE THREAD

**Issue by adambirds** [assem-ch/django-jet-reboot#106]
I get the below errors:

fliplytics-fliplytics-backend-1          | 2024-02-18 05:15:40,853 - django.request - WARNING - Method Not Allowed (GET): /admin/logout/
fliplytics-fliplytics-backend-1          | Method Not Allowed: /admin/logout/
fliplytics-fliplytics-backend-1          | 2024-02-18 05:15:40,855 - django.request - WARNING - Method Not Allowed: /admin/logout/
fliplytics-fliplytics-backend-1          | HTTP GET /admin/logout/ 405 [0.01, 172.18.0.1:58730]

Its due to it being a get request not a post request.

**Comment by assem-ch** [comment]
fixed by @amadev , try to upgrade int `django-jet-reboot==1.3.9`
