### ISSUE TITLE
Future Maintenance or Alternatives?

### ISSUE THREAD

**Issue by GonzaloMachado** [assem-ch/django-jet-reboot#108]
Hi there,

I wanted to reach out to ask about the future maintenance of the library. I’ve noticed that there are several pull requests that have been open for a while, and I wanted to check if there are any plans to address these or if the library will continue to be actively maintained.

I appreciate the features Django Jet Reboot provides, it is an awesome admin interface but I’ve been exploring other alternatives, such as Django AdminLTE and various themes from AppSeed. However, I’ve encountered some issues with these alternatives, including problems with Admin model inlines and the lack of support for fieldset tabs, which are well-handled by Django Jet Reboot, amongs others.

I would love to hear from other users or contributors if they have any recommendations for alternatives that offer similar functionality.

Thank you for your time and for developing this library. I look forward to your response!

**Comment by assem-ch** [comment]
Hey Gonzalo, I can keep maintaining this repo , as personally I use it it my projects. However I will still need help with fixes and testing, I'll setup github ci for autopublish so any one of contributors can release
