### ISSUE TITLE
Django jet with django admin autocomplete_fields

### ISSUE THREAD

**Issue by emiraldo** [assem-ch/django-jet-reboot#26]
I have a problem when I use django admin autocomplete_fields, this duplicates the field, any way to use autocomplete safely?

Thanks a lot! 😃

**Comment by assem-ch** [comment]
checking

**Comment by assem-ch** [comment]
@emiraldo can you please show how to reproduce

**Comment by emiraldo** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/7389161/159759075-8f4138e1-4dc1-44e3-ba6b-a8a9ebad433a.png">
<img width="444" alt="image" src="https://user-images.githubusercontent.com/7389161/159759100-aeeae002-8c05-4192-bb9f-67169e5c13ec.png">

**Comment by johnunar** [comment]
@emiraldo Django-jet automatically makes foreign key fields autocomplete, there is no need for specifying `autocomplete_fields` manually in the admin class.
