### ISSUE TITLE
Migration does work with custom user-model

### ISSUE THREAD

**Issue by patrickRauer** [assem-ch/django-jet-reboot#31]
Hey,

in the case that someone use a custom User model with a UUID instead of (Big)Integer as primary key, the migrations fail for (at least) a postgresql. 
As far as I see, the error comes from the migration fiels, which declare "user" as a PositiveIntegerField, first, and then alter "user" to ForeignKey. The cast for the second step won't work, if the User model has a non-integer field as its primary key.

Squashing or regenerating of the migration fields should solve the problem.

**Comment by assem-ch** [comment]
try this release : django-jet-reboot==1.3.1 , related to PR #32
