### ISSUE TITLE
Where do I get the $65 commercial license for Jet mentioned in this article? 

### ISSUE THREAD

**Issue by torrinworx** [assem-ch/django-jet-reboot#37]
Article: https://betterprogramming.pub/a-better-admin-for-your-django-app-b6302ae06847

I'm want to use Jet Reboot on my commercial website and just wanted to know if I can with the current license or where I can buy the commercial license?

Thank you for your time!

**Comment by assem-ch** [comment]
This is a reboot for the official Django jet which is discontinued, so we provide no commercial version, and I think the official owner doesn't do as well.

**Comment by torrinworx** [comment]
Ah ok thank you
