### ISSUE TITLE
fieldsets option

### ISSUE THREAD

**Issue by mickbad** [assem-ch/django-jet-reboot#39]
Hello,

I recently migrate to Django 4 and I use your jet modification interface. Thanks for your help to use it

But I use fieldsets in my admin panel (model) like this
```
        fieldsets = (
                (None, {'fields': (
                        'identification',
                        'date_joined',
                )}),
                ('options', {
                        'fields': (
                        'image_logo',
.....
```

In previous jet module, I have tabs but not now with this version
Is there an option to get tabs navigation in admin panel ?

thanks for your help :)

Mick

**Comment by assem-ch** [comment]
This should be a change related to django 4, is it showing tabs in django 3?

**Comment by mickbad** [comment]
in django3 I have same issue but I think it's my configuration because some input are strange

![image](https://user-images.githubusercontent.com/31075343/172905104-b60b5a5c-7a7e-40b9-81f8-d93f3c161b81.png)

in django admin panel, all alright

**Comment by mickbad** [comment]
In fact (oulala i'm tired)
with django 3.0 works
with django 4.0 doesn't work
