### ISSUE TITLE
Connection refused by localhost when trying to add a foreign key model inside a model

### ISSUE THREAD

**Issue by adhdisdev** [assem-ch/django-jet-reboot#48]
I have 2 models, one has a foreign key pointing to the other model. When I press "Add item" in the first model, I can press the plus button next to the foreign key field to add another to that model, but when I click it, it says "Connection refused by localhost".

`class Currency(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False)

class Item(models.Model):
    name = models.CharField(max_length=200, verbose_name="Megnevezés", blank=False)
    curr = models.ForeignKey(Currency, max_length=50, blank=False, on_delete=models.CASCADE)
`

screenshot: https://imgur.com/a/f1AFAY1

Django version: 4.0.6
jet version: newest.

**Comment by Alejandroacho** [comment]
Hi @adhdisdev,

Can you try to add this to your Jet settings:
`X_FRAME_OPTIONS = "ALLOWALL"`

This worked for me as you can see in [this PR](https://github.com/Alejandroacho/BackendTemplate/pull/61).

**Comment by adhdisdev** [comment]
Oh, yes it works! Thank you!

Is it possible for the dev to put this in the readme? Would be a great timesaver!
