### ISSUE TITLE
Inlines are wrongly displayed

### ISSUE THREAD

**Issue by bb4L** [assem-ch/django-jet-reboot#51]
Hey there

I just tried to use django-jet-reboot with ModelAdmin and multiple StackedInline unfortunately they don't get rendered as tabs (as before) but just below the modeladmin. 

any ideas what/if i'm doing something wrong? Or how this could be fixed?

**Comment by cobia** [comment]
You can try updating to the latest version 1.3.2 which also addresses this issue.
