### ISSUE TITLE
Pagination is not formatted correctly on the list display pages

### ISSUE THREAD

**Issue by cobia** [assem-ch/django-jet-reboot#53]
When the number of pages exceed 10 on a list display page, pagination breaks. The 3 dots are misplaced. I believe that they are supposed to be inserted into the "pages-wrapper" element followed by the last 2 pages in the pagination list, instead they are position just outside "pages-wrapper" element. See screenshot below.

This is tested on an installation of jet-reboot version=1.3.1 with no other packages installed. Django version=3.2.13. Tested in Chrome, Firefox, Edge, Chromium.

![image](https://user-images.githubusercontent.com/105749/195483040-a8550ebd-65c5-4a68-aea4-4ddd3716875f.png)

**Comment by assem-ch** [comment]
I guess this is one of django 2 to django 3 breaking changes

**Comment by xtlc** [comment]
this is still happening a year later. Unfortunately the rendering of the form does not happen in jinja but in js/jquery for that part I think. Any chance of fixing this? js is not my strong suite unfortunately.

**Comment by assem-ch** [comment]
released the fix by @cobia in release 1.3.9
