### ISSUE TITLE
Cannot Select all objects on a list display page 

### ISSUE THREAD

**Issue by cobia** [assem-ch/django-jet-reboot#54]
Usually, when selecting all objects on a list display page, it will only select the objects that are actually shown on the page, but then it gives options to select all objects. The option to "select all" is usually shown beside the actions field. Below is a screenshot which shows what i'm seeing. You can see in the html code, that the information exists, but it's hidden from view due to CSS rules. 

![image](https://user-images.githubusercontent.com/105749/195490132-e142371b-8759-4f79-be8f-aa5ffed2e4cd.png)

**Comment by cobia** [comment]
After further reviewing, it looks like removing lines 386-388 from _changelist.scss would resolve this issue, but i'm not sure if there are further implications:

suggested fix: remove the below from _changelist.scss

```
    span.all, span.action-counter, span.clear, span.question {
        display: none;
    }
```

**Comment by assem-ch** [comment]
@cobia Hey, I would say since that line is only related to _changelist.scss, we can easily test it, if you can go for a PR and we have few persons to test it

**Comment by GonzaloMachado** [comment]
Hello!
@assem-ch  Any updates on this last PR?

**Comment by assem-ch** [comment]
merged, please try to upgrade to`django-jet-reboot==1.3.9`
