### ISSUE TITLE
[Question] Makemigrations denied, what is the best practice to resolve?

### ISSUE THREAD

**Issue by scheung38** [assem-ch/django-jet-reboot#63]
Trying to generate makemigration files from local.yml : 

`docker-compose -f local.yml run --rm django python manage.py makemigrations  `        

1. Why jet and dashboard migration files went to /usr/local/lib/python3.10/site-packages folder and not to my local migrations folder as in the 0001_initial.py migration?

Migrations for 'dashboard':
  /usr/local/lib/python3.10/site-packages/jet/dashboard/migrations/0003_alter_userdashboardmodule_id.py
    - Alter field id on userdashboardmodule
Migrations for 'jet':
  /usr/local/lib/python3.10/site-packages/jet/migrations/0002_alter_bookmark_id_alter_pinnedapplication_id.py
    - Alter field id on bookmark
    - Alter field id on pinnedapplication
Migrations for 'paf':
  arthur_paf/paf/migrations/0001_initial.py
    - Create model AddressImpSet
    - Create model BuildingName

EDIT: it is trying to create it not does not exist:

cat: /usr/local/lib/python3.10/site-packages/jet/dashboard/migrations/0003_alter_userdashboardmodule_id.py: No such file or directory

cat: /usr/local/lib/python3.10/site-packages/jet/migrations/0002_alter_bookmark_id_alter_pinnedapplication_id.py: No such file or directory

2. But using production.yml:

`sudo docker-compose -f production.yml run --rm django python manage.py makemigrations
`
WARN[0000] The "MONGO_USERNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MONGO_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MONGO_HOST" variable is not set. Defaulting to a blank string. 
WARN[0000] The "MONGO_PORT" variable is not set. Defaulting to a blank string. 
[+] Running 1/1
 ⠿ Container mongo  Recreated                                                                  0.2s
[+] Running 1/1
 ⠿ Container mongo  Started                                                                    0.4s
DATABASE_URL inside entrypoint: mongodb://@mongo:27017/?authMechanism=SCRAM-SHA-1
Migrations for 'dashboard':
  /usr/local/lib/python3.10/site-packages/jet/dashboard/migrations/0003_alter_userdashboardmodule_id.py
    - Alter field id on userdashboardmodule
Traceback (most recent call last):
  File "/app/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 98, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/makemigrations.py", line 214, in handle
    self.write_migration_files(changes)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/makemigrations.py", line 256, in write_migration_files
    with open(writer.path, "w", encoding="utf-8") as fh:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.10/site-packages/jet/dashboard/migrations/0003_alter_userdashboardmodule_id.py'

Why is it now saying permission error?

Do we change chmod in /usr/local/lib to make it writable?

**Comment by assem-ch** [comment]
be sure you are calling the manage.py of the project and not the global one
