### ISSUE TITLE
Migration fails when using UUID

### ISSUE THREAD

**Issue by iamalmiir** [assem-ch/django-jet-reboot#64]
User model with a UUID instead of BIGINT, the migrations fail for PostgreSQL.
tried django-jet-reboot==1.3.1/1.3.3  still fails.

Error message:
return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: cannot cast type integer to uuid
LINE 1: ..." ALTER COLUMN "user_id" TYPE uuid USING "user_id"::uuid, AL...

**Comment by playma** [comment]
How did you solve it?

**Comment by iamalmiir** [comment]
Hey there, I hope you are doing great. I’m late but I still hope you will find my answer useful. 
So what I’ve done is: 
I installed django-jet-reboot then after that I added it to installed apps in settings.py and in urls.py.

After that I ran this command: `python manage.py migrate jet && python manage.py collectstatic`.  _Make sure to clear your browser cache_ 
You also wanna make sure that your templates settings are set right. There is no  need to run `python manage.py makemigrations.` for this purpose.
You can look up my project for more info [https://github.com/iamalmiir/ar_realty_backend.git](url)
I hope I helped a little, please feel free to reach out to me and this time I will respond on time :)

**Comment by iamalmiir** [comment]
Hey there, I hope you are doing great. I’m late but I still hope you will find my answer useful. 

So what I’ve done is I just excluded ‘jet.dashboard’ but kept ‘jet’.
I know that this is not a perfect solution but it’s the only one I have right now.

**Comment by playma** [comment]
@iamalmiir Thank you, I do the same thing...

**Comment by assem-ch** [comment]
It can fixed by re-generating `django-jet` migrations inside your project like that:
MIGRATION_MODULES = {
    "jet": "your_app.migrations.jet",
}
