### ISSUE TITLE
AccessTokenWidget.render() got an unexpected keyword argument 'renderer'

### ISSUE THREAD

**Issue by vispar-tech** [assem-ch/django-jet-reboot#75]
TypeError at /jet/dashboard/module/21/
AccessTokenWidget.render() got an unexpected keyword argument 'renderer'

when uses yandex metrika and click to login
<img width="400" alt="image" src="https://user-images.githubusercontent.com/85240536/218742214-60bd92de-b23d-40b0-a4c8-4b2c7d985a8f.png">

needs to add rendered=None to render function class AccessTokenWidget

**Comment by layred** [comment]
Django                     4.1.7
django-jet-reboot          1.3.3

**Comment by layred** [comment]
Django 4.1.7
django-jet-reboot 1.3.3

**Comment by xtlc** [comment]
I also run into this error as soon as I define a custom widget for the admin and I could get around it by using the somewhat newer version of method signature of `render`:

from:

`def render(self, name, value, attrs=None):`

to:

`def render(self, name, value, attrs=None, renderer=None):`

**Comment by assem-ch** [comment]
released 1.3.9
