### ISSUE TITLE
No collaboration info

### ISSUE THREAD

**Issue by johnnyunar** [assem-ch/django-jet-reboot#78]
Hi!

@assem-ch  - You mention that this project needs more collaborators. I want to start collaborating but can't find any working contact or collaboration info. Is the project still active?

**Comment by assem-ch** [comment]
Hey @johnunar , we dont have any external channel , only github issues and prs for now. If you are interested in contributing you can pick some issues and try to fix them, I will be happy to answer your questions. You can also review the open PRs.
