### ISSUE TITLE
Serving jet staticfiles with Django storages adding "amp;" to query string params resulting in 403 unautharized access

### ISSUE THREAD

**Issue by Jihad** [assem-ch/django-jet-reboot#93]
Not sure if this related to jet, but would love if anyone knows why?

Some staticfiles links have wrong params, what i noticed that they are only related to "django-jet" package. 

Normal Django staticfiles URL:

    https://daal.nyc3.digitaloceanspaces.com/static/css/admin.css?AWSAccessKeyId=****&Signature=***&Expires=1694226003

Django JET staticfiles URL:

    https://daal.nyc3.digitaloceanspaces.com/static/jet/css/icons/style.css?AWSAccessKeyId=*****&amp;Signature=*****&amp;Expires=1694226003&v=1.3.3

This is causing request headers to have invalid names:
[![Signature is now "amp;Signature:" param causing the issues][1]][1]

  [1]: https://i.stack.imgur.com/fmYYx.png

Note sure what is causing this? I couldn't find out why

**Comment by foundyengineer** [comment]
any progress on this issue?

**Comment by Jihad** [comment]
> any progress on this issue?

Nope, I just made the few files public and avoided my problem the easy way like a champ :-)

**Comment by assem-ch** [comment]
this seems related to jet_append_version , jet trying to add version to every static file url.

**Comment by assem-ch** [comment]
@foundyengineer can you make static files public, I dont think they need to be as signed urls

**Comment by derkweijers** [comment]
I was able to fix this by adding the following to my AWS/S3 [config](https://github.com/TheSpaceDevs/spaceflightnewsapi/blob/main/snapy/settings.py#L180):
`AWS_QUERYSTRING_AUTH = False`

Hopefully this will help others as well!

**Comment by ryanovas** [comment]
This is not completed and still an issue in 2025. There should be a setting to disable this behaviour or simply not do it at all.
