### ISSUE TITLE
Custom user issue

### ISSUE THREAD

**Issue by m3h-D** [assem-ch/django-jet-reboot#94]
when I am using CustomUser model I get this error:
`django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'service.CustomUser' that has not been installed`
I think the issue is the order of the apps in INSTALLED_APPS, I tried to put my service app above the 'jet' in INSTALLED_APPS, but some other errors were raised.

one solution:
maybe use BigIntegerField instead of Foreignkey for user relationships in jet models?

**Comment by assem-ch** [comment]
I think this has no relation to django-jet-reboot, be sure you are importing your app in `INSTALLED_APPS` before changing `AUTH_USER_MODEL`
