### ISSUE TITLE
Disable django-jet-reboot for a given admin site

### ISSUE THREAD

**Issue by sougrinoma-sawadogo** [assem-ch/django-jet-reboot#96]
Hi,
I have installed django-jet-reboot on my django project
I am using custom admin sites (the default one and a custom one)
I would like to disable djang-jet-reboot for the default site while keeping it on the custom admin site

I have posted a question about it on stackoverflow:

[Link to post](https://stackoverflow.com/questions/5420990/django-admin-using-different-templates-for-two-admin-site)

Your help will be appreciated,

Thanks in advance!

**Comment by assem-ch** [comment]
Hey, I see you get your answer in stack-overflow: https://stackoverflow.com/a/5433301. closing
