### ISSUE TITLE
Migration DatabaseError: ORA-00957: duplicate column name

### ISSUE THREAD

**Issue by elieserme** [assem-ch/django-jet-reboot#99]
Hello!

When execute migrate the following query cause Database Error on Oracle:

ALTER TABLE "DASHBOARD_USERDASHBOARDMODULE" RENAME COLUMN "USER" TO "USER_ID"

Please help me

**Comment by MarcBarlett** [comment]
try the following two steps
`python manage.py squashmigrations dashboard 0002`
`python manage.py migrate`

I had a different error changing column type on column "USER" using Postgres and squashing those two migrations helped

**Comment by assem-ch** [comment]
@MarcBarlett merged , thank you
